CREATE TEMP FUNCTION do(line STRING) AS ((
  SELECT ANY_VALUE(c HAVING MIN(i)) || ANY_VALUE(c HAVING MAX(i))
  FROM UNNEST(SPLIT(line, '')) c WITH OFFSET i
  WHERE REGEXP_CONTAINS(c, r'\d')
));

SELECT SUM(CAST(do(line) AS INT64))
FROM aoc2023.d1p1
